// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/codigo/Lexer.flex

package codigo;
import static codigo.Tokens.*;
//import java_cup.runtime.Symbol;

@SuppressWarnings("fallthrough")
public final class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\1\1\4"+
    "\1\5\5\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\12\16\1\0\1\17\1\20\1\21\1\22"+
    "\2\0\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\2\31\1\34\1\35\1\36\1\37\2\31"+
    "\1\40\1\41\1\42\1\31\1\43\4\31\1\0\1\44"+
    "\1\0\1\45\1\0\1\46\1\47\1\31\1\50\1\51"+
    "\1\52\1\31\1\53\1\31\1\54\2\31\1\55\1\31"+
    "\1\56\1\57\2\31\1\60\1\61\1\62\6\31\1\63"+
    "\1\0\1\64\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\14\16\1\17\1\1\1\20\1\21\1\22\1\0\1\23"+
    "\1\0\1\24\1\0\1\25\1\0\1\26\1\27\16\16"+
    "\1\30\1\16\1\0\1\23\1\0\1\12\7\16\1\31"+
    "\11\16\1\25\1\32\11\16\1\33\2\16\1\34\1\35"+
    "\7\16\1\36\1\37\4\16\1\40\4\16\1\41\1\42"+
    "\1\43\3\16\1\44\4\16\1\45\1\46\1\47\1\50"+
    "\1\16\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\65\0\u0109"+
    "\0\65\0\65\0\65\0\u013e\0\u0173\0\65\0\u01a8\0\u01dd"+
    "\0\65\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\65\0\u048e\0\65"+
    "\0\65\0\65\0\324\0\65\0\u04c3\0\65\0\u04f8\0\u052d"+
    "\0\u0562\0\65\0\65\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813"+
    "\0\u0848\0\u087d\0\u08b2\0\u048e\0\324\0\u08e7\0\u0562\0\u091c"+
    "\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0212\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37"+
    "\0\65\0\u0212\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u0212\0\u0e49\0\u0e7e\0\u0212\0\u0212"+
    "\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u0212"+
    "\0\u0212\0\u1026\0\u105b\0\u1090\0\u10c5\0\u0212\0\u10fa\0\u112f"+
    "\0\u1164\0\u1199\0\u0212\0\u0212\0\u0212\0\u11ce\0\u1203\0\u1238"+
    "\0\u0212\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u0212\0\u0212\0\u0212"+
    "\0\u0212\0\u1341\0\u0212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\2\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\22\1\23\1\24\1\25\1\26\1\22"+
    "\1\27\1\30\1\31\1\32\2\22\1\33\1\34\1\22"+
    "\1\35\1\2\1\36\1\37\14\22\1\40\1\41\66\0"+
    "\2\3\103\0\1\42\43\0\2\43\1\0\2\43\1\44"+
    "\36\43\1\45\20\43\10\0\1\46\64\0\1\47\4\0"+
    "\1\50\63\0\1\51\1\0\1\15\61\0\1\52\72\0"+
    "\1\53\61\0\1\22\4\0\21\22\3\0\14\22\20\0"+
    "\1\22\4\0\14\22\1\54\4\22\3\0\1\55\13\22"+
    "\20\0\1\22\4\0\4\22\1\56\14\22\3\0\14\22"+
    "\20\0\1\22\4\0\13\22\1\57\2\22\1\60\2\22"+
    "\3\0\7\22\1\61\4\22\20\0\1\22\4\0\10\22"+
    "\1\62\10\22\3\0\1\63\13\22\20\0\1\22\4\0"+
    "\1\64\20\22\3\0\14\22\20\0\1\22\4\0\13\22"+
    "\1\65\5\22\3\0\14\22\20\0\1\22\4\0\4\22"+
    "\1\66\14\22\3\0\10\22\1\67\3\22\20\0\1\22"+
    "\4\0\10\22\1\70\10\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\3\22\1\71\10\22\20\0\1\22"+
    "\4\0\10\22\1\72\10\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\3\22\1\73\10\22\2\0\46\74"+
    "\1\44\16\74\2\43\1\0\2\43\1\75\36\43\1\45"+
    "\20\43\10\47\1\76\54\47\2\50\1\0\62\50\16\0"+
    "\1\77\64\0\1\22\4\0\12\22\1\100\6\22\3\0"+
    "\14\22\20\0\1\22\4\0\21\22\3\0\2\22\1\101"+
    "\6\22\1\102\2\22\20\0\1\22\4\0\5\22\1\103"+
    "\13\22\3\0\14\22\20\0\1\22\4\0\17\22\1\104"+
    "\1\22\3\0\14\22\20\0\1\22\4\0\2\22\1\105"+
    "\16\22\3\0\14\22\20\0\1\22\4\0\21\22\3\0"+
    "\13\22\1\106\20\0\1\22\4\0\13\22\1\107\5\22"+
    "\3\0\14\22\20\0\1\22\4\0\21\22\3\0\6\22"+
    "\1\110\5\22\20\0\1\22\4\0\2\22\1\111\16\22"+
    "\3\0\14\22\20\0\1\22\4\0\10\22\1\112\10\22"+
    "\3\0\14\22\20\0\1\22\4\0\4\22\1\113\14\22"+
    "\3\0\14\22\20\0\1\22\4\0\21\22\3\0\4\22"+
    "\1\114\7\22\20\0\1\22\4\0\4\22\1\115\14\22"+
    "\3\0\14\22\20\0\1\22\4\0\21\22\3\0\1\116"+
    "\13\22\20\0\1\22\4\0\13\22\1\117\5\22\3\0"+
    "\14\22\20\0\1\22\4\0\21\22\3\0\11\22\1\120"+
    "\2\22\2\0\10\47\1\76\4\47\1\121\47\47\16\0"+
    "\1\22\4\0\14\22\1\122\4\22\3\0\14\22\20\0"+
    "\1\22\4\0\21\22\3\0\3\22\1\123\10\22\20\0"+
    "\1\22\4\0\21\22\3\0\1\124\13\22\20\0\1\22"+
    "\4\0\10\22\1\125\10\22\3\0\14\22\20\0\1\22"+
    "\4\0\14\22\1\126\4\22\3\0\14\22\20\0\1\22"+
    "\4\0\15\22\1\127\3\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\3\22\1\130\10\22\20\0\1\22"+
    "\4\0\21\22\3\0\12\22\1\131\1\22\20\0\1\22"+
    "\4\0\4\22\1\132\14\22\3\0\14\22\20\0\1\22"+
    "\4\0\2\22\1\133\16\22\3\0\14\22\20\0\1\22"+
    "\4\0\15\22\1\134\3\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\5\22\1\135\6\22\20\0\1\22"+
    "\4\0\13\22\1\136\5\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\6\22\1\137\5\22\20\0\1\22"+
    "\4\0\14\22\1\140\4\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\2\22\1\141\11\22\20\0\1\22"+
    "\4\0\21\22\3\0\7\22\1\142\4\22\20\0\1\22"+
    "\4\0\21\22\3\0\1\22\1\143\12\22\20\0\1\22"+
    "\4\0\13\22\1\144\5\22\3\0\14\22\20\0\1\22"+
    "\4\0\13\22\1\145\5\22\3\0\14\22\20\0\1\22"+
    "\4\0\10\22\1\146\10\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\11\22\1\147\2\22\20\0\1\22"+
    "\4\0\21\22\3\0\10\22\1\150\3\22\20\0\1\22"+
    "\4\0\15\22\1\151\3\22\3\0\14\22\20\0\1\22"+
    "\4\0\10\22\1\152\10\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\1\22\1\153\12\22\20\0\1\22"+
    "\4\0\17\22\1\154\1\22\3\0\14\22\20\0\1\22"+
    "\4\0\21\22\3\0\1\155\13\22\20\0\1\22\4\0"+
    "\21\22\3\0\1\156\13\22\20\0\1\22\4\0\21\22"+
    "\3\0\13\22\1\157\20\0\1\22\4\0\10\22\1\160"+
    "\10\22\3\0\14\22\20\0\1\22\4\0\2\22\1\161"+
    "\16\22\3\0\14\22\20\0\1\22\4\0\1\22\1\162"+
    "\17\22\3\0\14\22\20\0\1\22\4\0\21\22\3\0"+
    "\10\22\1\163\3\22\20\0\1\22\4\0\14\22\1\164"+
    "\4\22\3\0\14\22\20\0\1\22\4\0\21\22\3\0"+
    "\10\22\1\165\3\22\20\0\1\22\4\0\15\22\1\166"+
    "\3\22\3\0\14\22\20\0\1\22\4\0\21\22\3\0"+
    "\2\22\1\167\11\22\20\0\1\22\4\0\21\22\3\0"+
    "\3\22\1\170\10\22\20\0\1\22\4\0\15\22\1\171"+
    "\3\22\3\0\14\22\20\0\1\22\4\0\4\22\1\172"+
    "\14\22\3\0\14\22\20\0\1\22\4\0\10\22\1\173"+
    "\10\22\3\0\14\22\20\0\1\22\4\0\1\174\20\22"+
    "\3\0\14\22\20\0\1\22\4\0\21\22\3\0\3\22"+
    "\1\175\10\22\20\0\1\22\4\0\21\22\3\0\11\22"+
    "\1\176\2\22\20\0\1\22\4\0\16\22\1\177\2\22"+
    "\3\0\14\22\20\0\1\22\4\0\15\22\1\200\3\22"+
    "\3\0\14\22\20\0\1\22\4\0\16\22\1\201\2\22"+
    "\3\0\14\22\20\0\1\22\4\0\21\22\3\0\11\22"+
    "\1\202\2\22\20\0\1\22\4\0\21\22\3\0\10\22"+
    "\1\203\3\22\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4982];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\1\1\3\11\2\1\1\11"+
    "\2\1\1\11\14\1\1\11\1\1\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\1\1\0\2\11\20\1\1\0"+
    "\1\1\1\0\22\1\1\11\62\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

    public String lexeme;

    public int getLinea() {
        return yyline + 1;
    }

    public int getColumna() {
        return yycolumn + 1;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                //System.out.println("End Of File alcanzado");
    return null;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { lexeme = yytext();
            System.err.println("Símbolo no reconocido: " + yytext()
                + " en línea " + getLinea()
                + ", columna " + getColumna());
            return ERROR;
            }
          // fall through
          case 42: break;
          case 2:
            { /*Ingnorar los espacios */
            }
          // fall through
          case 43: break;
          case 3:
            { lexeme = yytext(); return PARENTESIS_ABRE;
            }
          // fall through
          case 44: break;
          case 4:
            { lexeme = yytext(); return PARENTESIS_CIERRA;
            }
          // fall through
          case 45: break;
          case 5:
            { lexeme = yytext(); return OP_MULTIPLICACION;
            }
          // fall through
          case 46: break;
          case 6:
            { lexeme = yytext(); return OP_SUMA;
            }
          // fall through
          case 47: break;
          case 7:
            { lexeme = yytext(); return COMA;
            }
          // fall through
          case 48: break;
          case 8:
            { lexeme = yytext(); return OP_RESTA;
            }
          // fall through
          case 49: break;
          case 9:
            { lexeme = yytext(); return OP_DIVISION;
            }
          // fall through
          case 50: break;
          case 10:
            { lexeme = yytext();  System.out.println("TOKEN: NUM-> " + lexeme); return Numero;
            }
          // fall through
          case 51: break;
          case 11:
            { lexeme = yytext(); return PUNTO_COMA;
            }
          // fall through
          case 52: break;
          case 12:
            { lexeme = yytext(); return OP_MENOR;
            }
          // fall through
          case 53: break;
          case 13:
            { lexeme = yytext(); return OP_MAYOR;
            }
          // fall through
          case 54: break;
          case 14:
            { lexeme = yytext(); System.out.println("TOKEN: ID -> " + lexeme); return Identificador;
            }
          // fall through
          case 55: break;
          case 15:
            { lexeme = yytext(); return OP_POTENCIA;
            }
          // fall through
          case 56: break;
          case 16:
            { lexeme = yytext(); return LLAVE_ABRE;
            }
          // fall through
          case 57: break;
          case 17:
            { lexeme = yytext(); return LLAVE_CIERRA;
            }
          // fall through
          case 58: break;
          case 18:
            { lexeme = yytext(); return OP_DIFERENTE;
            }
          // fall through
          case 59: break;
          case 19:
            { lexeme = yytext(); return Cadena;
            }
          // fall through
          case 60: break;
          case 20:
            { lexeme = yytext(); return OP_POTENCIA_DOBLE;
            }
          // fall through
          case 61: break;
          case 21:
            { lexeme = yytext(); return COMENTARIO;
            }
          // fall through
          case 62: break;
          case 22:
            { lexeme = yytext(); return ASIGNACION;
            }
          // fall through
          case 63: break;
          case 23:
            { lexeme = yytext(); return OP_IGUALDAD;
            }
          // fall through
          case 64: break;
          case 24:
            { lexeme = yytext(); return CONTROL_SI;
            }
          // fall through
          case 65: break;
          case 25:
            { lexeme = yytext(); return RESERVADA_FIN;
            }
          // fall through
          case 66: break;
          case 26:
            { lexeme = yytext(); return COMO;
            }
          // fall through
          case 67: break;
          case 27:
            { lexeme = yytext(); return LEER;
            }
          // fall through
          case 68: break;
          case 28:
            { lexeme = yytext(); return TIPO_REAL;
            }
          // fall through
          case 69: break;
          case 29:
            { lexeme = yytext(); return CONTROL_SINO;
            }
          // fall through
          case 70: break;
          case 30:
            { lexeme = yytext(); return VALOR_FALSO;
            }
          // fall through
          case 71: break;
          case 31:
            { lexeme = yytext(); return CONTROL_HACER;
            }
          // fall through
          case 72: break;
          case 32:
            { lexeme = yytext(); return TIPO_CADENA;
            }
          // fall through
          case 73: break;
          case 33:
            { lexeme = yytext(); return TIPO_ENTERO;
            }
          // fall through
          case 74: break;
          case 34:
            { lexeme = yytext(); return RESERVADA_INICIO;
            }
          // fall through
          case 75: break;
          case 35:
            { lexeme = yytext(); return TIPO_LOGICO;
            }
          // fall through
          case 76: break;
          case 36:
            { lexeme = yytext(); return DEFINIR;
            }
          // fall through
          case 77: break;
          case 37:
            { lexeme = yytext(); return TIPO_CARACTER;
            }
          // fall through
          case 78: break;
          case 38:
            { lexeme = yytext(); return CONTROL_ENTONCES;
            }
          // fall through
          case 79: break;
          case 39:
            { lexeme = yytext(); return ESCRIBIR;
            }
          // fall through
          case 80: break;
          case 40:
            { lexeme = yytext(); return CONTROL_MIENTRAS;
            }
          // fall through
          case 81: break;
          case 41:
            { lexeme = yytext(); return VALOR_VERDADERO;
            }
          // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
