
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

import java_cup.runtime.*;
import java.util.HashMap;
import java_cup.parser;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\017\000\002\002\004\000\002\002\005\000\002\003" +
    "\004\000\002\003\003\000\002\004\007\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\006\003\000\002\006\003\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\004\007\004\001\002\000\010\023\013\024" +
    "\014\026\011\001\002\000\004\002\006\001\002\000\004" +
    "\002\001\001\002\000\004\004\017\001\002\000\012\010" +
    "\016\023\013\024\014\026\011\001\002\000\004\004\ufff3" +
    "\001\002\000\012\010\ufffe\023\ufffe\024\ufffe\026\ufffe\001" +
    "\002\000\004\004\ufff5\001\002\000\004\004\ufff4\001\002" +
    "\000\012\010\uffff\023\uffff\024\uffff\026\uffff\001\002\000" +
    "\004\002\000\001\002\000\004\031\020\001\002\000\010" +
    "\004\024\005\021\006\023\001\002\000\014\032\ufff8\033" +
    "\ufff8\034\ufff8\035\ufff8\044\ufff8\001\002\000\014\032\027" +
    "\033\025\034\031\035\030\044\026\001\002\000\014\032" +
    "\ufff6\033\ufff6\034\ufff6\035\ufff6\044\ufff6\001\002\000\014" +
    "\032\ufff7\033\ufff7\034\ufff7\035\ufff7\044\ufff7\001\002\000" +
    "\010\004\024\005\021\006\023\001\002\000\012\010\ufffd" +
    "\023\ufffd\024\ufffd\026\ufffd\001\002\000\010\004\024\005" +
    "\021\006\023\001\002\000\010\004\024\005\021\006\023" +
    "\001\002\000\010\004\024\005\021\006\023\001\002\000" +
    "\014\032\ufffa\033\ufffa\034\ufffa\035\ufffa\044\ufffa\001\002" +
    "\000\014\032\ufff9\033\ufff9\034\ufff9\035\ufff9\044\ufff9\001" +
    "\002\000\014\032\ufffc\033\ufffc\034\031\035\030\044\ufffc" +
    "\001\002\000\014\032\ufffb\033\ufffb\034\031\035\030\044" +
    "\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\004\002\004\001\001\000\010\003\007\004" +
    "\011\006\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\004\014\006\006\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\034\001\001\000\002\001\001\000\004\005\033\001\001" +
    "\000\004\005\032\001\001\000\004\005\031\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    // GUARDA LOS VALORES DE LAS VARIABLES
    public static HashMap<String, Object> tablaSimbolos = new HashMap<>();

    // GUARDA EL TIPO DE CADA VARIABLE
    public static HashMap<String, String> tipos = new HashMap<>();

    // PERMITE HACER PRUEBAS DESDE EL TECLADO
   public static void main(String[] args) throws Exception {

    java.io.Reader reader = new java.io.BufferedReader(
        new java.io.FileReader("./entrada.txt")
    );

    LexerCup lexer = new LexerCup(reader);

    Sintax p = new Sintax(lexer);

    p.parse();
}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action_part00000000(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= RESERVADA_INICIO ListaAsignaciones RESERVADA_FIN 
            {
              Object RESULT =null;
		
    System.out.println("Analisis completado.");
    RESULT = "Análisis completado";

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ListaAsignaciones ::= ListaAsignaciones Asignacion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ListaAsignaciones",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ListaAsignaciones ::= Asignacion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ListaAsignaciones",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Asignacion ::= Tipo Identificador ASIGNACION Exp PUNTO_COMA 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		String tipo = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		

        String tipoStr = tipo;
        String idStr = id;
        Object valor = val;

         //pruebas
        System.out.println("TIPO: " + tipoStr);
        System.out.println("VALOR: " + valor);
        System.out.println("CLASE: " + valor.getClass());
         //***************************************************************


        if (tipoStr.equals("entero") && valor instanceof Integer) {

            tablaSimbolos.put(idStr, valor);
            tipos.put(idStr, tipoStr);

            System.out.println("Asignacion valida: "
                    + idStr + " = " + valor);

        } else if (tipoStr.equals("real")
                && valor instanceof Double) {

            tablaSimbolos.put(idStr, valor);
            tipos.put(idStr, tipoStr);

            System.out.println("Asignacion valida: "
                    + idStr + " = " + valor);

        } else if (tipoStr.equals("cadena")
                && valor instanceof String) {

            tablaSimbolos.put(idStr, valor);
            tipos.put(idStr, tipoStr);

            System.out.println("Asignacion valida: "
                    + idStr + " = " + valor);

        } else {

            System.err.println(
                "Error de tipo: valor incompatible."
            );
        }

        RESULT = null;

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Asignacion",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Exp ::= Exp OP_SUMA Exp 
            {
              Object RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object left = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object right = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        if (left instanceof Integer
                && right instanceof Integer) {

            RESULT = (Integer) left
                    + (Integer) right;

        } else if (left instanceof Number
                && right instanceof Number) {

            RESULT =
                ((Number) left).doubleValue()
                +
                ((Number) right).doubleValue();

        } else {

            System.err.println(
                "Error de tipos en suma"
            );

            RESULT = 0;
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Exp ::= Exp OP_RESTA Exp 
            {
              Object RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object left = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object right = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        if (left instanceof Integer
                && right instanceof Integer) {

            RESULT = (Integer) left
                    - (Integer) right;

        } else if (left instanceof Number
                && right instanceof Number) {

            RESULT =
                ((Number) left).doubleValue()
                -
                ((Number) right).doubleValue();

        } else {

            System.err.println(
                "Error de tipos en resta"
            );

            RESULT = 0;
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Exp ::= Exp OP_MULTIPLICACION Exp 
            {
              Object RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object left = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object right = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        if (left instanceof Integer
                && right instanceof Integer) {

            RESULT = (Integer) left
                    * (Integer) right;

        } else if (left instanceof Number
                && right instanceof Number) {

            RESULT =
                ((Number) left).doubleValue()
                *
                ((Number) right).doubleValue();

        } else {

            System.err.println(
                "Error de tipos en multiplicacion"
            );

            RESULT = 0;
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Exp ::= Exp OP_DIVISION Exp 
            {
              Object RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object left = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object right = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        if (left instanceof Integer
                && right instanceof Integer) {

            RESULT = (Integer) left
                    / (Integer) right;

        } else if (left instanceof Number
                && right instanceof Number) {

            RESULT =
                ((Number) left).doubleValue()
                /
                ((Number) right).doubleValue();

        } else {

            System.err.println(
                "Error de tipos en division"
            );

            RESULT = 0;
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Exp ::= Numero 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        String texto = num;

        if (texto.contains(".")) {

            RESULT = Double.parseDouble(texto);

        } else {

            RESULT = Integer.parseInt(texto);
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Exp ::= Identificador 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		

        String nombre = id;

        if (tablaSimbolos.containsKey(nombre)) {

            RESULT = tablaSimbolos.get(nombre);

        } else {

            System.err.println(
                "Variable no definida: " + nombre
            );

            RESULT = 0;
        }

    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Exp ::= LITERAL_CADENA 
            {
              Object RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = cad.replace("\"", "");
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Exp",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Tipo ::= TIPO_ENTERO 
            {
              String RESULT =null;
		 RESULT = "entero"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Tipo ::= TIPO_REAL 
            {
              String RESULT =null;
		 RESULT = "real"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Tipo ::= TIPO_CADENA 
            {
              String RESULT =null;
		 RESULT = "cadena"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("Tipo",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
              return CUP$Sintax$do_action_part00000000(
                               CUP$Sintax$act_num,
                               CUP$Sintax$parser,
                               CUP$Sintax$stack,
                               CUP$Sintax$top);
    }
}

}
