
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LITERAL_ENTERO = 42;
  public static final int OP_MAYOR = 31;
  public static final int PARENTESIS_CIERRA = 38;
  public static final int TIPO_REAL = 19;
  public static final int LITERAL_REAL = 41;
  public static final int CONTROL_HACER = 11;
  public static final int OP_MULTIPLICACION = 27;
  public static final int VALOR_VERDADERO = 22;
  public static final int OP_POTENCIA = 29;
  public static final int GRAFICAR = 16;
  public static final int SIGNO_IGUAL = 47;
  public static final int RESERVADA_INICIO = 5;
  public static final int TIPO_CARACTER = 20;
  public static final int ESCRIBIR = 14;
  public static final int COMO = 13;
  public static final int OP_DIFERENTE = 34;
  public static final int LITERAL_CARACTER = 43;
  public static final int PUNTO_COMA = 35;
  public static final int LITERAL_CADENA = 4;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 28;
  public static final int TIPO_ENTERO = 18;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int COMENTARIO = 44;
  public static final int OP_RESTA = 26;
  public static final int CONTROL_ENTONCES = 8;
  public static final int RESERVADA_FIN = 6;
  public static final int LLAVE_ABRE = 39;
  public static final int ERROR = 46;
  public static final int ASIGNACION = 24;
  public static final int VALOR_FALSO = 23;
  public static final int OP_POTENCIA_DOBLE = 30;
  public static final int COMENTARIO_MULTILINEA = 45;
  public static final int CONTROL_SINO = 9;
  public static final int CONTROL_MIENTRAS = 10;
  public static final int Identificador = 2;
  public static final int LEER = 15;
  public static final int LLAVE_CIERRA = 40;
  public static final int DEFINIR = 12;
  public static final int OP_SUMA = 25;
  public static final int TIPO_CADENA = 21;
  public static final int CONTROL_SI = 7;
  public static final int Numero = 3;
  public static final int TIPO_LOGICO = 17;
  public static final int OP_IGUALDAD = 33;
  public static final int PARENTESIS_ABRE = 37;
  public static final int OP_MENOR = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Numero",
  "LITERAL_CADENA",
  "RESERVADA_INICIO",
  "RESERVADA_FIN",
  "CONTROL_SI",
  "CONTROL_ENTONCES",
  "CONTROL_SINO",
  "CONTROL_MIENTRAS",
  "CONTROL_HACER",
  "DEFINIR",
  "COMO",
  "ESCRIBIR",
  "LEER",
  "GRAFICAR",
  "TIPO_LOGICO",
  "TIPO_ENTERO",
  "TIPO_REAL",
  "TIPO_CARACTER",
  "TIPO_CADENA",
  "VALOR_VERDADERO",
  "VALOR_FALSO",
  "ASIGNACION",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTIPLICACION",
  "OP_DIVISION",
  "OP_POTENCIA",
  "OP_POTENCIA_DOBLE",
  "OP_MAYOR",
  "OP_MENOR",
  "OP_IGUALDAD",
  "OP_DIFERENTE",
  "PUNTO_COMA",
  "COMA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "LITERAL_REAL",
  "LITERAL_ENTERO",
  "LITERAL_CARACTER",
  "COMENTARIO",
  "COMENTARIO_MULTILINEA",
  "ERROR",
  "SIGNO_IGUAL"
  };
}

