/* The following code was generated by JFlex 1.4.3 on 27/4/26, 22:32 */

package codigo;
import static codigo.Tokens.*;
//import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/4/26, 22:32 from the specification file
 * <tt>C:/Users/DELL/Downloads/AnalizadorLexico2/AnalizadorLexico2/src/codigo/Lexer.flex</tt>
 */
public final class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\2\0\1\3\22\0\1\3\1\52\1\61\4\0"+
    "\1\0\1\55\1\56\1\7\1\46\1\54\1\45\1\4\1\5\12\2"+
    "\1\0\1\53\1\44\1\51\1\50\2\0\1\22\1\25\1\12\1\24"+
    "\1\16\1\14\1\1\1\23\1\10\2\1\1\26\1\20\1\11\1\13"+
    "\2\1\1\21\1\15\1\17\1\1\1\42\4\1\1\0\1\62\1\0"+
    "\1\47\1\0\1\63\1\37\1\1\1\32\1\41\1\35\1\1\1\30"+
    "\1\1\1\31\2\1\1\40\1\1\1\33\1\27\2\1\1\36\1\43"+
    "\1\34\6\1\1\57\1\0\1\60\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\13\2"+
    "\1\7\1\10\1\11\1\12\1\13\2\1\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\2\1\1\0\1\22\1\0"+
    "\1\23\5\2\1\24\12\2\1\25\1\26\1\27\1\0"+
    "\1\30\2\0\1\3\1\0\4\2\1\31\14\2\1\30"+
    "\1\22\1\2\1\32\3\2\1\33\4\2\1\34\2\2"+
    "\1\35\5\2\1\36\4\2\1\37\3\2\1\40\1\2"+
    "\1\41\2\2\1\42\2\2\1\43\5\2\1\44\1\2"+
    "\1\45\1\46\1\47\1\50\1\2\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c"+
    "\0\u0340\0\u0374\0\u03a8\0\64\0\64\0\64\0\64\0\u03dc"+
    "\0\u0410\0\64\0\64\0\64\0\64\0\64\0\64\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\64\0\u0548\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750"+
    "\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\64\0\64\0\64"+
    "\0\u0444\0\64\0\u0888\0\u0478\0\u04ac\0\u08bc\0\u08f0\0\u0924"+
    "\0\u0958\0\u098c\0\150\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90"+
    "\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0444"+
    "\0\64\0\u0c30\0\150\0\u0c64\0\u0c98\0\u0ccc\0\150\0\u0d00"+
    "\0\u0d34\0\u0d68\0\u0d9c\0\150\0\u0dd0\0\u0e04\0\150\0\u0e38"+
    "\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\150\0\u0f3c\0\u0f70\0\u0fa4"+
    "\0\u0fd8\0\150\0\u100c\0\u1040\0\u1074\0\150\0\u10a8\0\150"+
    "\0\u10dc\0\u1110\0\150\0\u1144\0\u1178\0\150\0\u11ac\0\u11e0"+
    "\0\u1214\0\u1248\0\u127c\0\150\0\u12b0\0\150\0\150\0\150"+
    "\0\150\0\u12e4\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\5\1\7"+
    "\1\10\1\3\1\11\1\3\1\12\1\13\1\14\1\3"+
    "\1\15\1\16\1\3\1\17\1\20\1\3\1\21\13\3"+
    "\1\22\1\3\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\2\1\41\65\0\2\3\5\0\34\3\22\0\1\4"+
    "\1\0\1\42\62\0\1\5\2\0\1\5\62\0\1\43"+
    "\1\0\1\44\63\0\1\45\55\0\2\3\5\0\1\3"+
    "\1\46\32\3\21\0\2\3\5\0\3\3\1\47\23\3"+
    "\1\50\4\3\21\0\2\3\5\0\1\51\26\3\1\52"+
    "\4\3\21\0\2\3\5\0\1\53\33\3\21\0\2\3"+
    "\5\0\1\3\1\54\3\3\1\55\15\3\1\56\10\3"+
    "\21\0\2\3\5\0\1\57\33\3\21\0\2\3\5\0"+
    "\25\3\1\60\6\3\21\0\2\3\5\0\12\3\1\61"+
    "\21\3\21\0\2\3\5\0\6\3\1\62\25\3\21\0"+
    "\2\3\5\0\6\3\1\63\10\3\1\64\14\3\21\0"+
    "\2\3\5\0\25\3\1\65\6\3\65\0\1\66\67\0"+
    "\1\67\63\0\1\70\12\0\6\71\1\0\52\71\1\72"+
    "\1\73\1\71\63\74\1\72\2\0\1\75\61\0\6\43"+
    "\1\0\55\43\7\44\1\76\54\44\1\0\2\3\5\0"+
    "\1\77\33\3\21\0\2\3\5\0\10\3\1\100\23\3"+
    "\21\0\2\3\5\0\26\3\1\101\2\3\1\102\2\3"+
    "\21\0\2\3\5\0\1\3\1\103\32\3\21\0\2\3"+
    "\5\0\30\3\1\104\3\3\21\0\2\3\5\0\1\3"+
    "\1\105\32\3\21\0\2\3\5\0\7\3\1\106\24\3"+
    "\21\0\2\3\5\0\2\3\1\107\31\3\21\0\2\3"+
    "\5\0\24\3\1\110\7\3\21\0\2\3\5\0\6\3"+
    "\1\111\25\3\21\0\2\3\5\0\27\3\1\112\4\3"+
    "\21\0\2\3\5\0\2\3\1\113\31\3\21\0\2\3"+
    "\5\0\4\3\1\114\27\3\21\0\2\3\5\0\6\3"+
    "\1\115\25\3\21\0\2\3\5\0\20\3\1\116\13\3"+
    "\21\0\2\3\5\0\26\3\1\117\5\3\20\0\6\71"+
    "\1\0\52\71\1\120\1\73\1\71\5\44\1\121\1\44"+
    "\1\76\54\44\1\0\2\3\5\0\2\3\1\122\31\3"+
    "\21\0\2\3\5\0\3\3\1\123\30\3\21\0\2\3"+
    "\5\0\27\3\1\124\4\3\21\0\2\3\5\0\25\3"+
    "\1\125\6\3\21\0\2\3\5\0\33\3\1\126\21\0"+
    "\2\3\5\0\3\3\1\127\30\3\21\0\2\3\5\0"+
    "\3\3\1\130\30\3\21\0\2\3\5\0\11\3\1\131"+
    "\22\3\21\0\2\3\5\0\25\3\1\132\6\3\21\0"+
    "\2\3\5\0\1\3\1\133\32\3\21\0\2\3\5\0"+
    "\30\3\1\134\3\3\21\0\2\3\5\0\6\3\1\135"+
    "\25\3\21\0\2\3\5\0\1\136\33\3\21\0\2\3"+
    "\5\0\11\3\1\137\22\3\21\0\2\3\5\0\21\3"+
    "\1\140\12\3\21\0\2\3\5\0\31\3\1\141\2\3"+
    "\21\0\2\3\5\0\1\142\33\3\21\0\2\3\5\0"+
    "\22\3\1\143\11\3\21\0\2\3\5\0\23\3\1\144"+
    "\10\3\21\0\2\3\5\0\17\3\1\145\14\3\21\0"+
    "\2\3\5\0\1\3\1\146\32\3\21\0\2\3\5\0"+
    "\1\147\33\3\21\0\2\3\5\0\26\3\1\150\5\3"+
    "\21\0\2\3\5\0\7\3\1\151\24\3\21\0\2\3"+
    "\5\0\11\3\1\152\22\3\21\0\2\3\5\0\1\3"+
    "\1\153\32\3\21\0\2\3\5\0\22\3\1\154\11\3"+
    "\21\0\2\3\5\0\27\3\1\155\4\3\21\0\2\3"+
    "\5\0\3\3\1\156\30\3\21\0\2\3\5\0\24\3"+
    "\1\157\7\3\21\0\2\3\5\0\27\3\1\160\4\3"+
    "\21\0\2\3\5\0\2\3\1\161\31\3\21\0\2\3"+
    "\5\0\15\3\1\162\16\3\21\0\2\3\5\0\17\3"+
    "\1\163\14\3\21\0\2\3\5\0\11\3\1\164\22\3"+
    "\21\0\2\3\5\0\1\165\33\3\21\0\2\3\5\0"+
    "\17\3\1\166\14\3\21\0\2\3\5\0\31\3\1\167"+
    "\2\3\21\0\2\3\5\0\25\3\1\170\6\3\21\0"+
    "\2\3\5\0\6\3\1\171\25\3\21\0\2\3\5\0"+
    "\1\172\33\3\21\0\2\3\5\0\12\3\1\173\21\3"+
    "\21\0\2\3\5\0\11\3\1\174\22\3\21\0\2\3"+
    "\5\0\25\3\1\175\6\3\21\0\2\3\5\0\26\3"+
    "\1\176\5\3\21\0\2\3\5\0\5\3\1\177\26\3"+
    "\21\0\2\3\5\0\11\3\1\200\22\3\21\0\2\3"+
    "\5\0\5\3\1\201\26\3\21\0\2\3\5\0\26\3"+
    "\1\202\5\3\21\0\2\3\5\0\17\3\1\203\14\3"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4888];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\21\1\4\11\2\1\6\11\2\1\1\0"+
    "\1\1\1\0\1\11\20\1\3\11\1\0\1\11\2\0"+
    "\1\1\1\0\22\1\1\11\62\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

    public String lexeme;

    public int getLinea() {
        return yyline + 1;
    }

    public int getColumna() {
        return yycolumn + 1;
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { lexeme = yytext(); return PUNTO_COMA;
          }
        case 42: break;
        case 29: 
          { lexeme = yytext(); return LEER;
          }
        case 43: break;
        case 33: 
          { lexeme = yytext(); return TIPO_CADENA;
          }
        case 44: break;
        case 22: 
          { lexeme = yytext(); return OP_IGUALDAD;
          }
        case 45: break;
        case 3: 
          { lexeme = yytext();  System.out.println("TOKEN: NUM-> " + lexeme); return Numero;
          }
        case 46: break;
        case 9: 
          { lexeme = yytext(); return OP_SUMA;
          }
        case 47: break;
        case 40: 
          { lexeme = yytext(); return CONTROL_MIENTRAS;
          }
        case 48: break;
        case 36: 
          { lexeme = yytext(); return DEFINIR;
          }
        case 49: break;
        case 13: 
          { lexeme = yytext(); return COMA;
          }
        case 50: break;
        case 25: 
          { lexeme = yytext(); return RESERVADA_FIN;
          }
        case 51: break;
        case 7: 
          { lexeme = yytext(); return OP_MENOR;
          }
        case 52: break;
        case 16: 
          { lexeme = yytext(); return LLAVE_ABRE;
          }
        case 53: break;
        case 4: 
          { /*Ingnorar los espacios */
          }
        case 54: break;
        case 34: 
          { lexeme = yytext(); return TIPO_ENTERO;
          }
        case 55: break;
        case 24: 
          { lexeme = yytext(); return Cadena;
          }
        case 56: break;
        case 39: 
          { lexeme = yytext(); return ESCRIBIR;
          }
        case 57: break;
        case 1: 
          { lexeme = yytext();
            System.err.println("Símbolo no reconocido: " + yytext()
                + " en línea " + getLinea()
                + ", columna " + getColumna());
            return ERROR;
          }
        case 58: break;
        case 27: 
          { lexeme = yytext(); return CONTROL_SINO;
          }
        case 59: break;
        case 37: 
          { lexeme = yytext(); return TIPO_CARACTER;
          }
        case 60: break;
        case 5: 
          { lexeme = yytext(); return OP_DIVISION;
          }
        case 61: break;
        case 21: 
          { lexeme = yytext(); return ASIGNACION;
          }
        case 62: break;
        case 18: 
          { lexeme = yytext(); return COMENTARIO;
          }
        case 63: break;
        case 6: 
          { lexeme = yytext(); return OP_MULTIPLICACION;
          }
        case 64: break;
        case 2: 
          { lexeme = yytext(); System.out.println("TOKEN: ID -> " + lexeme); return Identificador;
          }
        case 65: break;
        case 28: 
          { lexeme = yytext(); return TIPO_REAL;
          }
        case 66: break;
        case 20: 
          { lexeme = yytext(); return CONTROL_SI;
          }
        case 67: break;
        case 26: 
          { lexeme = yytext(); return COMO;
          }
        case 68: break;
        case 23: 
          { lexeme = yytext(); return OP_DIFERENTE;
          }
        case 69: break;
        case 14: 
          { lexeme = yytext(); return PARENTESIS_ABRE;
          }
        case 70: break;
        case 32: 
          { lexeme = yytext(); return RESERVADA_INICIO;
          }
        case 71: break;
        case 38: 
          { lexeme = yytext(); return CONTROL_ENTONCES;
          }
        case 72: break;
        case 17: 
          { lexeme = yytext(); return LLAVE_CIERRA;
          }
        case 73: break;
        case 35: 
          { lexeme = yytext(); return TIPO_LOGICO;
          }
        case 74: break;
        case 19: 
          { lexeme = yytext(); return OP_POTENCIA_DOBLE;
          }
        case 75: break;
        case 10: 
          { lexeme = yytext(); return OP_POTENCIA;
          }
        case 76: break;
        case 31: 
          { lexeme = yytext(); return CONTROL_HACER;
          }
        case 77: break;
        case 8: 
          { lexeme = yytext(); return OP_RESTA;
          }
        case 78: break;
        case 11: 
          { lexeme = yytext(); return OP_MAYOR;
          }
        case 79: break;
        case 15: 
          { lexeme = yytext(); return PARENTESIS_CIERRA;
          }
        case 80: break;
        case 41: 
          { lexeme = yytext(); return VALOR_VERDADERO;
          }
        case 81: break;
        case 30: 
          { lexeme = yytext(); return VALOR_FALSO;
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                //System.out.println("End Of File alcanzado");
    return null;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
