
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_Abierto = 53;
  public static final int Coma = 30;
  public static final int Parentesis_Cerrado = 15;
  public static final int If = 12;
  public static final int Rune = 42;
  public static final int Byte = 36;
  public static final int Default = 58;
  public static final int Package = 55;
  public static final int Var = 40;
  public static final int Operador = 18;
  public static final int Interface = 59;
  public static final int Else = 13;
  public static final int Reservadas = 20;
  public static final int Fallthrough = 25;
  public static final int Func = 23;
  public static final int Map = 29;
  public static final int Goto = 52;
  public static final int Error = 44;
  public static final int Select = 32;
  public static final int Corchete_Cerrado = 38;
  public static final int Punto = 33;
  public static final int Return = 27;
  public static final int Int = 47;
  public static final int Division = 10;
  public static final int Cadena = 28;
  public static final int For = 39;
  public static final int Parentesis_Abierto = 14;
  public static final int EOF = 0;
  public static final int AsignacionCorta = 49;
  public static final int Logico = 46;
  public static final int error = 1;
  public static final int Switch = 26;
  public static final int Import = 56;
  public static final int Integer = 4;
  public static final int PuntoyComa = 11;
  public static final int Struvt = 41;
  public static final int Breack = 34;
  public static final int ERROR = 19;
  public static final int Llave_Cerrado = 54;
  public static final int Chan = 35;
  public static final int Go = 16;
  public static final int Continue = 31;
  public static final int Case = 50;
  public static final int Const = 22;
  public static final int String = 24;
  public static final int Float64 = 5;
  public static final int Corchete_Abierto = 37;
  public static final int Identificador = 2;
  public static final int Struct = 17;
  public static final int Resta = 8;
  public static final int Type = 45;
  public static final int Defer = 57;
  public static final int Bool = 43;
  public static final int Multiplicacion = 9;
  public static final int Numero = 3;
  public static final int Suma = 7;
  public static final int Main = 51;
  public static final int Igual = 6;
  public static final int Range = 21;
  public static final int GO = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Numero",
  "Integer",
  "Float64",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "PuntoyComa",
  "If",
  "Else",
  "Parentesis_Abierto",
  "Parentesis_Cerrado",
  "Go",
  "Struct",
  "Operador",
  "ERROR",
  "Reservadas",
  "Range",
  "Const",
  "Func",
  "String",
  "Fallthrough",
  "Switch",
  "Return",
  "Cadena",
  "Map",
  "Coma",
  "Continue",
  "Select",
  "Punto",
  "Breack",
  "Chan",
  "Byte",
  "Corchete_Abierto",
  "Corchete_Cerrado",
  "For",
  "Var",
  "Struvt",
  "Rune",
  "Bool",
  "Error",
  "Type",
  "Logico",
  "Int",
  "GO",
  "AsignacionCorta",
  "Case",
  "Main",
  "Goto",
  "Llave_Abierto",
  "Llave_Cerrado",
  "Package",
  "Import",
  "Defer",
  "Default",
  "Interface"
  };
}

